# Generated by Django 2.2.16 on 2022-10-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221005_2144'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique subscription',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique subscription'),
        ),
    ]
